const options=[
 {key:'a',name:'全项紧凑',brief:'全部字段可见，大屏单行完成筛选。',note:'适合频繁组合多个条件；1440px 单行排列，窄一些的电脑窗口自动换行。'},
 {key:'b',name:'常用条件优先',brief:'门店、日期常驻，四项条件按需展开。',note:'与手机端 A 版一致。适合主要按门店和日期查看记录，筛选后会保留可移除的条件标签。'},
 {key:'c',name:'两行分组',brief:'六项始终可见，范围与内容分开排列。',note:'第一行：门店、日期、关键词。第二行：报账人、类别、备注。输入框更宽，便于填写复合条件。'}
];
function CanvasTools(){const [scale,setScale]=React.useState(1);React.useEffect(()=>{const handler=e=>{if(e.origin===location.origin&&e.data?.type==='__dc_zoom')setScale(e.data.scale)};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)},[]);return <div className="canvas-tools"><button onClick={()=>window.postMessage({type:'__dc_fit'},location.origin)}>适应窗口</button><button aria-label="缩小画布" onClick={()=>window.postMessage({type:'__dc_set_zoom',scale:scale/1.2},location.origin)}>−</button><span>{Math.round(scale*100)}%</span><button aria-label="放大画布" onClick={()=>window.postMessage({type:'__dc_set_zoom',scale:scale*1.2},location.origin)}>+</button></div>}
function Review(){const [selected,setSelected]=React.useState('b'),[view,setView]=React.useState('live'),[theme,setTheme]=React.useState('light'),[width,setWidth]=React.useState(1440),[scale,setScale]=React.useState(1);const frame=React.useRef(null),stage=React.useRef(null),current=options.find(o=>o.key===selected);
 function send(type){frame.current?.contentWindow?.postMessage({type,theme},location.origin)}
 React.useEffect(()=>{send('desktop-theme')},[theme]);
 React.useEffect(()=>{if(!stage.current)return;const observer=new ResizeObserver(entries=>setScale(Math.min(1,entries[0].contentRect.width/width)));observer.observe(stage.current);return()=>observer.disconnect()},[width,view]);
 return <><header className="review-head"><div><h1>/expense · 电脑端筛选布局</h1><p>沿用现有风格，比较信息密度与条件展开方式。</p></div><div className="top-tools"><button aria-pressed={view==='live'} onClick={()=>setView('live')}>交互预览</button><button aria-pressed={view==='compare'} onClick={()=>setView('compare')}>效果图对比</button><button aria-label={theme==='light'?'切换深色':'切换浅色'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?'◐ 深色':'◑ 浅色'}</button><a className="download-link" href="previews/comparison.png" target="_blank" rel="noreferrer">查看总览图 ↗</a></div></header><nav className="variant-row" aria-label="选择桌面方案">{options.map(o=><button key={o.key} className="variant-choice" aria-pressed={selected===o.key} onClick={()=>{setSelected(o.key);setView('live')}}><span className="letter">{o.key.toUpperCase()}</span><span><strong>{o.name}{o.key==='b'&&<span className="recommended">推荐</span>}</strong><small>{o.brief}</small></span></button>)}</nav>
 {view==='live'?<><div className="stage-meta"><p>{current.note}</p><div><select aria-label="电脑屏幕宽度" value={width} onChange={e=>setWidth(Number(e.target.value))}><option value="1280">1280 px</option><option value="1440">1440 px</option><option value="1600">1600 px</option></select><button onClick={()=>send('desktop-example')}>预填条件</button><button onClick={()=>send('desktop-reset')}>恢复初始</button><a href={`${selected}.html?theme=${theme}`} target="_blank" rel="noreferrer">实际尺寸 ↗</a></div></div><main className="stage-outer"><div className="stage" ref={stage}><div className="preview-window" style={{width:Math.min(width,width*scale),height:900*scale}}><iframe ref={frame} key={selected} src={`${selected}.html`} onLoad={()=>send('desktop-theme')} title={`${selected.toUpperCase()} ${current.name}`} style={{width,height:900,transform:`scale(${scale})`}}></iframe></div></div></main><p className="review-note">独立设计预览 · 虚构示例数据 · 可体验日期选择、复合筛选与重置 · 尚未实施桌面端改动</p></>:<div className="canvas-host"><CanvasTools></CanvasTools><DesignCanvas style={{height:'100%'}}><DCSection id="desktop" title="三种布局 · 同一组筛选字段" subtitle="可拖动、缩放与放大单版；点击画面打开交互版本。" gap={30}>{options.map(o=><DCArtboard key={o.key} id={o.key} label={`${o.key.toUpperCase()} · ${o.name}`} width={1440} height={940}><a href={`${o.key}.html?theme=${theme}`} target="_blank" rel="noreferrer"><img src={`previews/${o.key}-${theme}.png`} width="1440" height="940" alt={`${o.name}电脑端效果图`}></img></a></DCArtboard>)}</DCSection></DesignCanvas><div className="canvas-hint">滚轮缩放 · 拖动画布 · 双击空白处适应画面</div></div>}
 </>
}
ReactDOM.createRoot(document.getElementById('root')).render(<Review></Review>);
