const options=[
 {key:'a',name:'行内折叠',brief:'熟悉的表单，一次展开全部条件。',description:'门店与创建日期上下排列，保留完整标签。点“更多条件”展开四个输入框，查询后自动收起，并显示可移除的条件标签。',tradeoff:'适合最小改动。操作路径直观，展开时会把报账列表向下推。'},
 {key:'b',name:'紧凑工具栏',brief:'标签与内容横排，首屏更省空间。',description:'将门店、创建日期改为两行设置项。更多条件在原位置展开，报账人与类别双列排布；同年日期省略重复年份。',tradeoff:'适合高频查看记录。整体更紧凑，较长的输入内容需要横向移动光标查看。'},
 {key:'c',name:'底部面板',brief:'基础条件留在页面，复杂筛选单独操作。',description:'点“更多筛选”从底部打开面板，四项条件有完整输入空间。点“应用筛选”才生效；关闭面板会放弃面板内未应用的编辑。',tradeoff:'适合一次填写多个条件。需要多一次打开面板的操作，手机键盘出现时可滚动。'},
 {key:'d',name:'按项展开',brief:'四个条件入口，只展开当前需要的一项。',description:'门店与创建日期采用设置列表；下方四个小入口分别展开关键词、报账人、类别和备注。切换入口会保留已填内容。',tradeoff:'适合只调整一两个条件。可快速定位字段，同时核对多项内容需要切换入口。'}
];
function CanvasTools(){const [scale,setScale]=React.useState(1);React.useEffect(()=>{const handler=e=>{if(e.origin===location.origin&&e.data?.type==='__dc_zoom')setScale(e.data.scale)};window.addEventListener('message',handler);return()=>window.removeEventListener('message',handler)},[]);return <div className="canvas-tools"><button onClick={()=>window.postMessage({type:'__dc_fit'},location.origin)}>适应窗口</button><button aria-label="缩小画布" onClick={()=>window.postMessage({type:'__dc_set_zoom',scale:scale/1.2},location.origin)}>−</button><span>{Math.round(scale*100)}%</span><button aria-label="放大画布" onClick={()=>window.postMessage({type:'__dc_set_zoom',scale:scale*1.2},location.origin)}>+</button></div>}
function Review(){const [selected,setSelected]=React.useState('a'),[theme,setTheme]=React.useState('light'),[view,setView]=React.useState('live'),[width,setWidth]=React.useState('390');const frame=React.useRef(null);const current=options.find(o=>o.key===selected);
 function send(type){frame.current?.contentWindow?.postMessage({type,theme},location.origin)}
 React.useEffect(()=>{send('expense-preview-theme')},[theme]);
 return <><header className="review-header"><div className="review-title"><span className="eyebrow">/EXPENSE · MOBILE FILTERS</span><h1>让常用筛选，先被看见。</h1></div><div className="review-actions"><button aria-pressed={view==='live'} onClick={()=>setView('live')}>交互预览</button><button aria-pressed={view==='compare'} onClick={()=>setView('compare')}>四版对比</button><button aria-label={theme==='light'?'切换深色':'切换浅色'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?'◐':'◑'}</button></div></header>
 {view==='live'?<main className="workspace"><aside className="sidebar"><p className="sidebar-intro">门店、创建日期始终显示。<br></br>其余四项默认收起，沿用现有视觉风格。</p><div className="variant-list" aria-label="选择设计版本">{options.map(o=><button key={o.key} className="variant-card" aria-pressed={selected===o.key} onClick={()=>setSelected(o.key)}><span className="variant-letter">{o.key.toUpperCase()}</span><span className="variant-copy"><strong>{o.name}{o.key==='a'&&<span className="recommend">推荐</span>}</strong><small>{o.brief}</small></span></button>)}</div><div className="design-note"><h2>{current.key.toUpperCase()} / {current.name}</h2><p>{current.description}</p><p className="tradeoff">{current.tradeoff}</p><p className="sample-note">独立交互预览 · 列表为虚构示例数据<br></br>可体验日期选择、复合筛选、查询、重置与条件移除。尚未应用到业务页面。</p></div></aside><section className="stage" aria-label="手机交互预览"><div className="stage-tools"><label>屏幕宽度<select value={width} onChange={e=>setWidth(e.target.value)} aria-label="屏幕宽度"><option value="375">375 px</option><option value="390">390 px</option><option value="430">430 px</option></select></label><div><button onClick={()=>send('expense-preview-example')}>预填条件</button><button onClick={()=>send('expense-preview-reset')}>恢复初始</button></div></div><div className="preview-window" style={{width:Number(width)}}><iframe ref={frame} key={selected} src={`${selected}.html`} title={`方案 ${selected.toUpperCase()} ${current.name}`} onLoad={()=>send('expense-preview-theme')}></iframe></div><a className="direct-link" href={`${selected}.html?theme=${theme}`} target="_blank" rel="noreferrer">单独打开 {selected.toUpperCase()} 版 ↗</a></section></main>:<div className="canvas-host"><CanvasTools></CanvasTools><DesignCanvas style={{height:'100%'}}><DCSection id="filters" title="门店与创建日期常驻 · 四种折叠方式" subtitle="点击画面进入对应交互版本；默认收起状态，屏幕宽度 390 px。" gap={28}>{options.map(o=><DCArtboard key={o.key} id={o.key} label={`${o.key.toUpperCase()} · ${o.name}`} width={390} height={844}><a href={`${o.key}.html?theme=${theme}`} target="_blank" rel="noreferrer" aria-label={`打开 ${o.name} 交互预览`}><img src={`previews/${o.key}-${theme}.png`} width="390" height="844" alt={`${o.name}手机端默认收起效果`}></img></a></DCArtboard>)}</DCSection></DesignCanvas><div className="canvas-hint">滚轮缩放 · 拖动画布 · 双击空白处适应画面</div></div>}
 </>
}
ReactDOM.createRoot(document.getElementById('root')).render(<Review></Review>);
